package wellnus.reflection.command;

import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

import wellnus.command.Command;
import wellnus.common.WellNusLogger;
import wellnus.exception.BadCommandException;
import wellnus.reflection.feature.QuestionList;
import wellnus.reflection.feature.ReflectUi;

//@@author wenxin-c
/**
 * Get all the questions that are in the favorite list.
 */
public class FavoriteCommand extends Command {
    public static final String COMMAND_DESCRIPTION = "fav - Get the list of questions that have been added to "
            + "the favorite list.";
    public static final String COMMAND_USAGE = "usage: fav";
    public static final String COMMAND_KEYWORD = "fav";
    private static final String PAYLOAD = "";
    private static final String FEATURE_NAME = "reflect";
    private static final String INVALID_COMMAND_MSG = "Invalid command issued, expected 'fav'!";
    private static final String INVALID_ARGUMENTS_MSG = "Invalid arguments given to 'fav'!";
    private static final String INVALID_PAYLOAD = "Invalid payload given to 'fav'!";
    private static final String INVALID_COMMAND_NOTES = "fav command " + COMMAND_USAGE;
    private static final String COMMAND_KEYWORD_ASSERTION = "The key should be fav.";
    private static final String COMMAND_PAYLOAD_ASSERTION = "The payload should be empty.";
    private static final String INDEX_OUT_OF_BOUND_MSG = "Invalid index given, index is out of bound!";
    private static final String EMPTY_FAV_LIST = "There is nothing in favorite list, "
            + "please get reflection questions first!";
    private static final int ARGUMENT_PAYLOAD_SIZE = 1;
    private static final Logger LOGGER = WellNusLogger.getLogger("ReflectFavCommandLogger");
    private static final ReflectUi UI = new ReflectUi();
    private QuestionList questionList;

    /**
     * Set up the argument-payload pairs for this command.<br/>
     * Pass in a questionList object from ReflectionManager to access the list of favorite questions.
     *
     * @param arguments Argument-payload pairs from users
     * @param questionList Object that contains the data about questions
     */
    public FavoriteCommand(HashMap<String, String> arguments, QuestionList questionList) {
        super(arguments);
        this.questionList = questionList;
    }

    /**
     * Get the command itself.
     *
     * @return Command: get
     */
    @Override
    protected String getCommandKeyword() {
        return COMMAND_KEYWORD;
    }

    /**
     * Get the name of the feature in which this fav command is generated.
     *
     * @return Feature name: reflect
     */
    @Override
    protected String getFeatureKeyword() {
        return FEATURE_NAME;
    }

    /**
     * Method to ensure that developers add in a command usage.
     * <p>
     * For example, for the 'add' command in AtomicHabit package: <br>
     * "usage: add --name (name of habit)"
     *
     * @return String of the proper usage of the habit
     */
    @Override
    public String getCommandUsage() {
        return COMMAND_USAGE;
    }

    /**
     * Method to ensure that developers add in a description for the command.
     * <p>
     * For example, for the 'add' command in AtomicHabit package: <br>
     * "add - add a habit to your list"
     *
     * @return String of the description of what the command does
     */
    @Override
    public String getCommandDescription() {
        return COMMAND_DESCRIPTION;
    }

    /**
     * Entry point to this command.<br/>
     */
    @Override
    public void execute() {
        try {
            validateCommand(getArguments());
        } catch (BadCommandException invalidCommand) {
            LOGGER.log(Level.INFO, INVALID_COMMAND_MSG);
            UI.printErrorFor(invalidCommand, INVALID_COMMAND_NOTES);
            return;
        }
        if (!questionList.hasFavQuestions()) {
            UI.printOutputMessage(EMPTY_FAV_LIST);
            return;
        }
        try {
            String outputString = questionList.getFavQuestions();
            UI.printOutputMessage(outputString);
        } catch (IndexOutOfBoundsException indexOutOfBoundsException) {
            LOGGER.log(Level.WARNING, INDEX_OUT_OF_BOUND_MSG);
            UI.printErrorFor(indexOutOfBoundsException, INVALID_COMMAND_NOTES);
        }
    }

    /**
     * Validate the command.<br/>
     * <br/>
     * Conditions for command to be valid:<br/>
     * <li>Only one argument-payload pair
     * <li>The pair contains key: fav
     * <li>Payload is empty
     * Whichever mismatch will cause the command to be invalid.
     *
     * @param commandMap Argument-Payload map generated by CommandParser
     * @throws BadCommandException If an invalid command is given
     */
    @Override
    public void validateCommand(HashMap<String, String> commandMap) throws BadCommandException {
        if (commandMap.size() != ARGUMENT_PAYLOAD_SIZE) {
            throw new BadCommandException(INVALID_ARGUMENTS_MSG);
        } else if (!commandMap.containsKey(COMMAND_KEYWORD)) {
            throw new BadCommandException(INVALID_COMMAND_MSG);
        } else if (!commandMap.get(COMMAND_KEYWORD).equals(PAYLOAD)) {
            throw new BadCommandException(INVALID_PAYLOAD);
        }
        assert getArguments().containsKey(COMMAND_KEYWORD) : COMMAND_KEYWORD_ASSERTION;
        assert getArguments().get(COMMAND_KEYWORD).equals(PAYLOAD) : COMMAND_PAYLOAD_ASSERTION;
    }
}

