@startuml
'https://plantuml.com/class-diagram
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR


Package command {
    Class CommandParser {
        + parseUserInput(String)
        + getMainArgument(String)
        - splitIntoCommands(String)
        - getArgumentFromCommand(String)
        - getPayloadFromCommand(String)
    }
}

Package manager{
    Class "{abstract}\nManager" as Manager {
        # commandParser : CommandParser
        + getCommandParser()
    }
}

Class AtomicHabitManager {
    # commandParser : CommandParser
    + getCommandParser()
}

Class ReflectionManager {
    # commandParser : CommandParser
    + getCommandParser()
}

CommandParser "1" -- Manager : contains <
Manager <|-- AtomicHabitManager
Manager <|-- ReflectionManager



@enduml