@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package reflection <<Rectangle>>{
Package command <<Rectangle>>{
class GetCommand{
-reflectUi : ReflectUi
+getRandomQuestions() : ArrayList<ReflectionQuestion>
}
class HomeCommand{
-reflectUi : ReflectUi
}
class LikeCommand{
-reflectUi : ReflectUi
+addFavQuestion(questionIndex: String)
+mapInputToQuestion() : HashMap<Integer, Integer>
}
class FavCommand{
-reflectUi : ReflectUi
}
}

Package feature <<Rectangle>>{
class ReflectionManager{
-reflectUi : ReflectUi
+executeCommands() : void
+runEventDriver() : void
}
class ReflectUi{
#printLogoWithSeparator(logo : String) : void
}
class ReflectionQuestion{
-questionDescription : String
}
class QuestionList{
-setUpQuestions() : void
+getQuestions() : ArrayList<ReflectionQuestion>
}
class RandomNumberGenerator{
+generateRandomNumbers() : Set<Integer>
}
}
}

class TextUi{
+printOutputMessage(message : String) : void
+printErrorFor(exception : Exception, additionalMessage : String) : void
}
class "{abstract}\nManager" as Manager{
#{abstract}setSupportedCommands() : void
#{abstract}runEventDriver() : void
}
class "{abstract}\nCommand" as Command{
-arguments : HashMap<String, String>
#{abstract}execute : void
#{abstract}validateCommand(commandMap: HashMap<String, String>) : void
}
class Storage

ReflectionManager --> "1" QuestionList : create >
ReflectionManager --|> Manager
ReflectionManager ..> GetCommand : execute >
ReflectionManager ..> HomeCommand : execute >
ReflectionManager ..> LikeCommand : execute >
ReflectionManager ..> FavCommand : execute >
GetCommand ..> QuestionList
FavCommand ..> QuestionList
LikeCommand ..> QuestionList
HomeCommand ..> QuestionList
QuestionList --> "10" ReflectionQuestion : contains >
QuestionList --> "1" ReflectUi : uses >
QuestionList --> "1" Storage
QuestionList --> "1" RandomNumberGenerator : uses >
ReflectUi --|> TextUi
GetCommand --|> Command
HomeCommand --|> Command
LikeCommand --|> Command
FavCommand --|> Command
HomeCommand ..> ReflectionManager : calls >
@enduml
