package wellnus.reflection;

import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

import wellnus.command.Command;
import wellnus.exception.BadCommandException;

/**
 * Home command to return back to WellNUS++ main interface.
 *
 * @@author wenxin-c
 */
public class HomeCommand extends Command {
    public static final String COMMAND_DESCRIPTION = "home - Return back to the main menu of WellNUS++.";
    public static final String COMMAND_USAGE = "usage: home";
    private static final Logger LOGGER = Logger.getLogger("ReflectHomeCommandLogger");
    private static final String FEATURE_NAME = "reflect";
    private static final String COMMAND_KEYWORD = "home";
    private static final String PAYLOAD = "";
    private static final String INVALID_COMMAND_MSG = "Command is invalid.";
    private static final String INVALID_COMMAND_NOTES = "Please check the available commands "
            + "and the format of commands.";
    private static final String EMPTY_ARGUMENT_PAYLOAD_ASSERTION = "The argument-payload pair cannot be empty!";
    private static final String COMMAND_KEYWORD_ASSERTION = "The key should be return.";
    private static final String COMMAND_PAYLOAD_ASSERTION = "The payload should be empty.";
    private static final String HOME_MESSAGE = "How do you feel after reflecting on yourself?"
            + System.lineSeparator() + "Hope you have gotten some takeaways from self reflection, see you again!!";
    private static final int ARGUMENT_PAYLOAD_SIZE = 1;
    private static final int EMPTY_ARGUMENT_PAYLOAD = 0;
    private static final ReflectUi UI = new ReflectUi();
    private HashMap<String, String> argumentPayload;
    private QuestionList questionList;

    /**
     * Set up the argument-payload pairs for this command.<br/>
     * Pass in a questionList object from ReflectionManager to manipulate history data.
     *
     * @param arguments Argument-payload pairs from users
     * @param questionList Object that contains the data about questions
     * @throws BadCommandException If an invalid command is given
     */
    public HomeCommand(HashMap<String, String> arguments, QuestionList questionList) throws BadCommandException {
        super(arguments);
        this.argumentPayload = getArguments();
        this.questionList = questionList;
        assert argumentPayload.size() > EMPTY_ARGUMENT_PAYLOAD : EMPTY_ARGUMENT_PAYLOAD_ASSERTION;
    }

    /**
     * Get the command itself.
     *
     * @return Command: home
     */
    @Override
    protected String getCommandKeyword() {
        return COMMAND_KEYWORD;
    }

    /**
     * Get the name of the feature in which this home command is generated.
     *
     * @return Feature name: reflect
     */
    @Override
    protected String getFeatureKeyword() {
        return FEATURE_NAME;
    }

    /**
     * Method to ensure that developers add in a command usage.
     * <p>
     * For example, for the 'add' command in AtomicHabit package: <br>
     * "usage: add --name (name of habit)"
     *
     * @return String of the proper usage of the habit
     */
    @Override
    public String getCommandUsage() {
        return COMMAND_USAGE;
    }

    /**
     * Method to ensure that developers add in a description for the command.
     * <p>
     * For example, for the 'add' command in AtomicHabit package: <br>
     * "add - add a habit to your list"
     *
     * @return String of the description of what the command does
     */
    @Override
    public String getCommandDescription() {
        return COMMAND_DESCRIPTION;
    }

    /**
     * Main entry point of this command.<br/>
     * Return back to WellNUS++ main interface and clear the questionList history data.
     */
    @Override
    public void execute() {
        try {
            validateCommand(this.argumentPayload);
        } catch (BadCommandException invalidCommand) {
            LOGGER.log(Level.INFO, INVALID_COMMAND_MSG);
            UI.printErrorFor(invalidCommand, INVALID_COMMAND_NOTES);
            return;
        }
        assert argumentPayload.containsKey(COMMAND_KEYWORD) : COMMAND_KEYWORD_ASSERTION;
        assert argumentPayload.get(COMMAND_KEYWORD).equals(PAYLOAD) : COMMAND_PAYLOAD_ASSERTION;
        UI.printOutputMessage(HOME_MESSAGE);
        if (!questionList.getRandomQuestionIndexes().isEmpty()) {
            questionList.clearRandomQuestionIndexes();
        }
        ReflectionManager.setIsExit(true);
    }

    /**
     * Validate the command.<br/>
     * <br/>
     * Conditions for command to be valid:<br/>
     * <li>Only one argument-payload pair
     * <li>The pair contains key: home
     * <li>Payload is empty
     * Whichever mismatch will cause the command to be invalid.
     *
     * @param commandMap Argument-Payload map generated by CommandParser
     * @throws BadCommandException If an invalid command is given
     */
    @Override
    public void validateCommand(HashMap<String, String> commandMap) throws BadCommandException {
        if (commandMap.size() != ARGUMENT_PAYLOAD_SIZE) {
            throw new BadCommandException(INVALID_COMMAND_MSG);
        } else if (!commandMap.containsKey(COMMAND_KEYWORD)) {
            throw new BadCommandException(INVALID_COMMAND_MSG);
        } else if (!commandMap.get(COMMAND_KEYWORD).equals(PAYLOAD)) {
            throw new BadCommandException(INVALID_COMMAND_MSG);
        }
    }
}

